development:
  adapter: postgresql
  encoding: unicode
  database: roommates_dev
  pool: 5
  username: postgres
  password: x0ct@llc0x

test:
  adapter: postgresql
  encoding: unicode
  database: roommates_test
  pool: 5
  username: postgres
  password: x0ct@llc0x

production:
  adapter: postgresql
  encoding: unicode
  database: roommates
  pool: 5
  username: postgres
  password: x0ct@llc0x
