development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: roommates_dev
  pool: 5
  username:  Frank
  password:

test:
  adapter: postgresql
  host: localhost
  database: roommates_test
  pool: 5
  username: Frank
  password:

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: roommates
  pool: 5
  username: Frank
  password:
